PortfoliWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortfoliWebsite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PortfoliWebsite/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortfoliWebsite.Controllers
{
    public class NavigationController : Controller
    {
        // GET: Navigation
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MyProjects()
        {
            return View();
        }
    }
}

PortfoliWebsite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PortfoliWebsite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PortfoliWebsite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="inner">

    <!--HOME-->
    <section id="home">
        <div class="container">

        </div>
    </section>
    <!--/.HOME END-->
    <!-- Header -->
    <header id="header">
        <a href="index.html" class="logo"><strong>Editorial</strong> by HTML5 UP</a>
        <ul class="icons">
            <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
            <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
            <li><a href="#" class="icon fa-snapchat-ghost"><span class="label">Snapchat</span></a></li>
            <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
            <li><a href="#" class="icon fa-medium"><span class="label">Medium</span></a></li>
        </ul>
    </header>

    <!-- Banner -->
    <section id="banner">
        <div class="content">
            <header>
                <h1>
                    Hi, I’m Hasib!!
                </h1>
            </header>
            <p>An Engineer, Free-thinker, Traveler!</p>
            <ul class="actions">
                <li><a href="#" class="button big">Learn More</a></li>
            </ul>
        </div>
        <span class="image object">
            <img src="~/Content/images/FB_IMG_1531691644825.jpg" alt="" />
        </span>
    </section>

    <!-- Section -->
    @*<section>
            <header class="major">
                <h2>Erat lacinia</h2>
            </header>
            <div class="features">
                <article>
                    <span class="icon fa-diamond"></span>
                    <div class="content">
                        <h3>Portitor ullamcorper</h3>
                        <p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
                    </div>
                </article>
                <article>
                    <span class="icon fa-paper-plane"></span>
                    <div class="content">
                        <h3>Sapien veroeros</h3>
                        <p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
                    </div>
                </article>
                <article>
                    <span class="icon fa-rocket"></span>
                    <div class="content">
                        <h3>Quam lorem ipsum</h3>
                        <p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
                    </div>
                </article>
                <article>
                    <span class="icon fa-signal"></span>
                    <div class="content">
                        <h3>Sed magna finibus</h3>
                        <p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
                    </div>
                </article>
            </div>
        </section>*@

    <!-- Section -->
    @*<section>
            <header class="major">
                <h2>Ipsum sed dolor</h2>
            </header>
            <div class="posts">
                <article>
                    <a href="#" class="image"><img src="~/Content/images/pic01.jpg" alt="" /></a>
                    <h3>Interdum aenean</h3>
                    <p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
                    <ul class="actions">
                        <li><a href="#" class="button">More</a></li>
                    </ul>
                </article>
                <article>
                    <a href="#" class="image"><img src="~/Content/images/pic02.jpg" alt="" /></a>
                    <h3>Nulla amet dolore</h3>
                    <p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
                    <ul class="actions">
                        <li><a href="#" class="button">More</a></li>
                    </ul>
                </article>
                <article>
                    <a href="#" class="image"><img src="~/Content/images/pic03.jpg" alt="" /></a>
                    <h3>Tempus ullamcorper</h3>
                    <p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
                    <ul class="actions">
                        <li><a href="#" class="button">More</a></li>
                    </ul>
                </article>
                <article>
                    <a href="#" class="image"><img src="~/Content/images/pic04.jpg" alt="" /></a>
                    <h3>Sed etiam facilis</h3>
                    <p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
                    <ul class="actions">
                        <li><a href="#" class="button">More</a></li>
                    </ul>
                </article>
                <article>
                    <a href="#" class="image"><img src="~/Content/images/pic05.jpg" alt="" /></a>
                    <h3>Feugiat lorem aenean</h3>
                    <p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
                    <ul class="actions">
                        <li><a href="#" class="button">More</a></li>
                    </ul>
                </article>
                <article>
                    <a href="#" class="image"><img src="~/Content/images/pic06.jpg" alt="" /></a>
                    <h3>Amet varius aliquam</h3>
                    <p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
                    <ul class="actions">
                        <li><a href="#" class="button">More</a></li>
                    </ul>
                </article>
            </div>
        </section>*@

</div>

PortfoliWebsite/Views/Navigation/MyProjects.cshtml
@{
    ViewBag.Title = "MyProjects";
}

<h2>MyProjects</h2>

PortfoliWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Content/css/main.css" />

    <title>@ViewBag.Title Portfolio</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="is-preload">
    <div id="wrapper">
        <div id="main">
            @RenderBody()
        </div>
        <!-- SideBar -->
        <div id="sidebar">
            <div class="inner">

                <!-- Search -->
                <section id="search" class="alt">
                    <form method="post" action="#">
                        <input type="text" name="query" id="query" placeholder="Search" />
                    </form>
                </section>

                <!-- Menu -->
                <nav id="menu">
                    <header class="major">
                        <h2>Menu</h2>
                    </header>
                    <ul>
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>
                            <span class="opener">About Me</span>
                            <ul>
                                <li>@Html.ActionLink("Hobbies", "About", "Home")</li>
                                <li><a href="#">Professional</a></li>
                            </ul>
                        </li>
                        <li><a href="#">@Html.ActionLink("My Projects", "MyProjects", "Navigation")</a></li>
                        <li><a href="#">Downloads</a></li>
                        <li><a href="#">@Html.ActionLink("Blogs", "MyProjects", "Navigation")</a></li>
                        <li><a href="#">@Html.ActionLink("Gallery", "MyProjects", "Navigation")</a></li>
                        <li><a href="#">@Html.ActionLink("Video", "MyProjects", "Navigation")</a></li>
                        <li><a href="#">Nihongo</a></li>
                    </ul>
                </nav>

                <section>
                    <header class="major">
                        <h2>Get in touch</h2>
                    </header>
                    <p>Contact me anytime!!</p>
                    <ul class="contact">
                        <li class="fa-envelope-o"><a href="#">hasibulhasan2009@gmail.com</a></li>
                        <li class="fa-phone">(+880) 17413-39123</li>
                        <li class="fa-home">
                            89/A-1, Barabag, Mirpur-2<br />
                            Dhaka, Bangladesh
                        </li>
                    </ul>
                </section>

                <!-- Footer -->
                <footer id="footer">
                    <p class="copyright">&copy; All Rights Reserved, @DateTime.Today.Year Md. Hasibul Hasan</p>
                </footer>

            </div>
        </div>
    </div>
    <script src="~/Scripts/js/jquery.min.js"></script>
    <script src="~/Scripts/js/browser.min.js"></script>
    <script src="~/Scripts/js/breakpoints.min.js"></script>
    <script src="~/Scripts/js/util.js"></script>
    <script src="~/Scripts/js/main.js"></script>
</body>
</html>









@*<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)*@